refactor: lint code

diff --git a/git-flow-support b/git-flow-support
--- a/git-flow-support
+++ b/git-flow-support
@@ -82,8 +82,8 @@ v,verbose         Verbose (more) output
 	# Parse arguments
 	parse_args "$@"
 
-	support_branches=$(git_local_branches_prefixed "$PREFIX")
-	if [ -z "$support_branches" ]; then
+	support_branches=$(git_local_branches_prefixed "${PREFIX}")
+	if [[ -z "${support_branches}" ]]; then
 		warn "No support branches exist."
 		warn ""
 		warn "You can start a new support branch:"
@@ -96,36 +96,36 @@ v,verbose         Verbose (more) output
 
 	# Determine column width first
 	width=0
-	for branch in $support_branches; do
+	for branch in ${support_branches}; do
 		len=${#branch}
-		width=$(max $width $len)
+		width=$(max "${width}" "${len}")
 	done
-	width=$(($width+3-${#PREFIX}))
+	width=$((${width}+3-${#PREFIX}))
 
-	for branch in $support_branches; do
-		base=$(git merge-base "$branch" "$MASTER_BRANCH")
-		master_sha=$(git rev-parse "$MASTER_BRANCH")
-		branch_sha=$(git rev-parse "$branch")
-		if [ "$branch" = "$current_branch" ]; then
+	for branch in ${support_branches}; do
+		base=$(git merge-base "${branch}" "${MASTER_BRANCH}")
+		master_sha=$(git rev-parse "${MASTER_BRANCH}")
+		branch_sha=$(git rev-parse "${branch}")
+		if [[ "${branch}" = "${current_branch}" ]]; then
 			printf "* "
 		else
 			printf "  "
 		fi
 		if flag verbose; then
-			printf "%-${width}s" "${branch#$PREFIX}"
-			if [ "$branch_sha" = "$master_sha" ]; then
+			printf "%-${width}s" "${branch#"${PREFIX}"}"
+			if [[ "${branch_sha}" = "${master_sha}" ]]; then
 				printf "(no commits yet)"
 			else
-				tagname=$(git name-rev --tags --no-undefined --name-only "$base")
-				if [ "$tagname" != "" ]; then
-					nicename=$tagname
+				tagname=$(git name-rev --tags --no-undefined --name-only "${base}")
+				if [[ "${tagname}" != "" ]]; then
+					nicename=${tagname}
 				else
-					nicename=$(git rev-parse --short "$base")
+					nicename=$(git rev-parse --short "${base}")
 				fi
-				printf "(based on $nicename)"
+				printf "(based on ${nicename})"
 			fi
 		else
-			printf "%s" "${branch#$PREFIX}"
+			printf "%s" "${branch#"${PREFIX}"}"
 		fi
 		echo
 	done
@@ -142,18 +142,18 @@ parse_args() {
 	eval set -- "${FLAGS_ARGV}"
 
 	# Read arguments into global variables
-	if [ -z $1 ]; then
+	if [[ -z "$1" ]]; then
 		VERSION=''
 	else
 		VERSION=$1
 	fi
 
-	if [ -z $2 ]; then
+	if [[ -z "$2" ]]; then
 		BASE=''
 	else
 		BASE=$2
 	fi
-	BRANCH=$PREFIX$VERSION
+	BRANCH=${PREFIX}${VERSION}
 }
 
 cmd_start() {
@@ -167,7 +167,7 @@ showcommands!     Show git commands while executing them
 F,[no]fetch       Fetch from origin before performing finish
 "
 	# Define flags
-	DEFINE_boolean 'fetch' false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean 'fetch' false "fetch from ${ORIGIN} before performing finish" F
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "support.start.fetch"   "fetch"
@@ -183,19 +183,19 @@ F,[no]fetch       Fetch from origin before performing finish
 
 	# Fetch remote changes
 	if flag fetch; then
-		git_fetch_branch "$ORIGIN" "$BASE"
+		git_fetch_branch "${ORIGIN}" "${BASE}"
 	fi
 
-	git_is_ancestor "$BASE" "$MASTER_BRANCH" || die "Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
+	git_is_ancestor "${BASE}" "${MASTER_BRANCH}" || die "Given base '${BASE}' is not a valid commit on '${MASTER_BRANCH}'."
 
-	require_branch_absent "$BRANCH"
+	require_branch_absent "${BRANCH}"
 
 	# Create branch
-	git_do checkout -b "$BRANCH" "$BASE" || die "Could not create support branch '$BRANCH'."
+	git_do checkout -b "${BRANCH}" "${BASE}" || die "Could not create support branch '${BRANCH}'."
 
 	echo
 	echo "Summary of actions:"
-	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
+	echo "- A new branch '${BRANCH}' was created, based on '${BASE}'"
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
 }
@@ -225,27 +225,27 @@ p,[no]preserve-merges  Preserve merges
 	parse_args "$@"
 
 	# Use current branch if no version is given
-	if [ "$VERSION" = "" ]; then
+	if [[ "${VERSION}" = "" ]]; then
 		gitflow_use_current_branch_version
 	fi
 
-	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
-	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+	BASE_BRANCH=$(gitflow_config_get_base_branch "${BRANCH}")
+	BASE_BRANCH=${BASE_BRANCH:-${DEVELOP_BRANCH}}
 
-	warn "Will try to rebase '$NAME' which is based on '$BASE_BRANCH'..."
+	warn "Will try to rebase '${NAME}' which is based on '${BASE_BRANCH}'..."
 	if ! git_config_bool_exists "rebase.autostash"; then
 		require_clean_working_tree
 	fi
-	require_branch "$BRANCH"
+	require_branch "${BRANCH}"
 
-	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't rebase the support branch '$BRANCH'."
+	git_local_branch_exists "${BASE_BRANCH}" || die "The base '${BASE_BRANCH}' doesn't exists locally or is not a branch. Can't rebase the support branch '${BRANCH}'."
 
-	git_do checkout -q "$BRANCH"  || die "Could not check out branch '$BRANCH'."
+	git_do checkout -q "${BRANCH}"  || die "Could not check out branch '${BRANCH}'."
 	if flag interactive; then
-		opts="$opts -i"
+		opts="${opts} -i"
 	fi
 	if flag preserve_merges; then
-		opts="$opts -p"
+		opts="${opts} -p"
 	fi
-	git_do rebase $opts "$BASE_BRANCH"
+	git_do rebase "${opts}" "${BASE_BRANCH}"
 }
diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -60,26 +60,26 @@ contains() {
 
 	case $1 in
 		*$2*)
-			return=$FLAGS_TRUE
+			return=${FLAGS_TRUE}
 			;;
 		*)
-			return=$FLAGS_FALSE
+			return=${FLAGS_FALSE}
 			;;
 	esac
-	return $return
+	return "${return}"
 }
 
 # Basic math
-min() { [ "$1" -le "$2" ] && echo "$1" || echo "$2"; }
-max() { [ "$1" -ge "$2" ] && echo "$1" || echo "$2"; }
+min() { [[ "$1" -le "$2" ]] && echo "$1" || echo "$2"; }
+max() { [[ "$1" -ge "$2" ]] && echo "$1" || echo "$2"; }
 
 # Basic string matching
-startswith() { [ "$1" != "${1#$2}" ]; }
-endswith() { [ "$1" != "${1%$2}" ]; }
+startswith() { [[ "$1" != "${1#"$2"}" ]]; }
+endswith() { [[ "$1" != "${1%"$2"}" ]]; }
 
 # Convenience functions for checking shFlags flags
-flag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -eq $FLAGS_TRUE ]; }
-noflag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -ne $FLAGS_TRUE ]; }
+flag() { local FLAG; eval FLAG='$FLAGS_'"$1"; [[ "${FLAG}" -eq "${FLAGS_TRUE}" ]]; }
+noflag() { local FLAG; eval FLAG='$FLAGS_'"$1"; [[ "${FLAG}" -ne "${FLAGS_TRUE}" ]]; }
 
 # check_boolean
 # Check if given value can be interpreted as a boolean
@@ -109,7 +109,7 @@ check_boolean() {
 		;;
 	esac
 	unset _value
-	return ${_return}
+	return "${_return}"
 }
 
 #
@@ -122,16 +122,16 @@ git_all_branches() { git for-each-ref --sort refname --format='%(refname:short)'
 git_all_tags() { git for-each-ref --format='%(refname:short)' refs/tags; }
 
 git_local_branches_prefixed() {
-	[ -z $1 ] && die "Prefix parameter missing." # This should never happen.
-	git for-each-ref --format='%(refname:short)' refs/heads/$1\* ;
+	[[ -z "$1" ]] && die "Prefix parameter missing." # This should never happen.
+	git for-each-ref --format='%(refname:short)' refs/heads/"$1"\* ;
 }
 
 git_current_branch() {
 	local branch_name
 
 	branch_name="$(git symbolic-ref --quiet HEAD)"
-	[ -z $branch_name ] && branch_name="(unnamed branch)" || branch_name="$(git for-each-ref --format='%(refname:short)' $branch_name)"
-	echo "$branch_name"
+	[[ -z "${branch_name}" ]] && branch_name="(unnamed branch)" || branch_name="$(git for-each-ref --format='%(refname:short)' "${branch_name}")"
+	echo "${branch_name}"
 }
 
 git_is_clean_working_tree() {
@@ -152,42 +152,42 @@ git_repo_is_headless() {
 }
 
 git_local_branch_exists() {
-	[ -n "$1" ] || die "Missing branch name"
-	[ -n "$(git for-each-ref --format='%(refname:short)' refs/heads/$1)" ]
+	[[ -n "$1" ]] || die "Missing branch name"
+	[[ -n "$(git for-each-ref --format='%(refname:short)' refs/heads/"$1")" ]]
 }
 
 git_remote_branch_exists() {
-	[ -n "$1" ] || die "Missing branch name"
-	[ -n "$(git for-each-ref --format='%(refname:short)' refs/remotes/$1)" ]
+	[[ -n "$1" ]] || die "Missing branch name"
+	[[ -n "$(git for-each-ref --format='%(refname:short)' refs/remotes/"$1")" ]]
 }
 
 git_remote_branch_delete() {
-	[ -n "$1" ] || die "Missing branch name"
-	if git_remote_branch_exists "$ORIGIN/$1"; then
-		git_do push "$ORIGIN" :"$1" || die "Could not delete the remote $1 in $ORIGIN."
+	[[ -n "$1" ]] || die "Missing branch name"
+	if git_remote_branch_exists "${ORIGIN}/$1"; then
+		git_do push "${ORIGIN}" :"$1" || die "Could not delete the remote $1 in ${ORIGIN}."
 		return 0
 	else
-		warn "Trying to delete the remote branch $1, but it does not exists in $ORIGIN"
+		warn "Trying to delete the remote branch $1, but it does not exists in ${ORIGIN}"
 		return 1
 	fi
 }
 
 git_branch_exists() {
-	[ -n "$1" ] || die "Missing branch name"
-	git_local_branch_exists "$1" || git_remote_branch_exists "$ORIGIN/$1"
+	[[ -n "$1" ]] || die "Missing branch name"
+	git_local_branch_exists "$1" || git_remote_branch_exists "${ORIGIN}/$1"
 }
 
 git_tag_exists() {
-	[ -n "$1" ] || die "Missing tag name"
-	[ -n "$(git for-each-ref --format='%(refname:short)' refs/tags/$1)" ]
+	[[ -n "$1" ]] || die "Missing tag name"
+	[[ -n "$(git for-each-ref --format='%(refname:short)' refs/tags/"$1")" ]]
 }
 
 git_config_bool_exists() {
 	local value
 
-	[ -n "$1" ] || die "Missing config option"
-	value=$(git config --get --bool $1)
-	[ "$value" = "true" ]
+	[[ -n "$1" ]] || die "Missing config option"
+	value=$(git config --get --bool "$1")
+	[[ "${value}" = "true" ]]
 }
 #
 # git_compare_refs()
@@ -206,13 +206,13 @@ git_compare_refs() {
 
 	commit1=$(git rev-parse "$1"^{})
 	commit2=$(git rev-parse "$2"^{})
-	if [ "$commit1" != "$commit2" ]; then
-		base=$(git merge-base "$commit1" "$commit2")
-		if [ $? -ne 0 ]; then
+	if [[ "${commit1}" != "${commit2}" ]]; then
+		base=$(git merge-base "${commit1}" "${commit2}")
+		if [[ $? -ne 0 ]]; then
 			return 4
-		elif [ "$commit1" = "$base" ]; then
+		elif [[ "${commit1}" = "${base}" ]]; then
 			return 1
-		elif [ "$commit2" = "$base" ]; then
+		elif [[ "${commit2}" = "${base}" ]]; then
 			return 2
 		else
 			return 3
@@ -234,7 +234,7 @@ git_is_branch_merged_into() {
 	base_hash=$(git rev-parse "$1"^{})
 
 	# If the hashes are equal, the branches are merged.
-	[ "$merge_hash" = "$base_hash" ]
+	[[ "${merge_hash}" = "${base_hash}" ]]
 }
 
 #
@@ -260,14 +260,14 @@ git_is_ancestor() {
 git_fetch_branch() {
 	local origin branch
 
-	[ -n "$1" ] || die "Missing origin"
-	[ -n "$2" ] || die "Missing branch name"
+	[[ -n "$1" ]] || die "Missing origin"
+	[[ -n "$2" ]] || die "Missing branch name"
 	origin="$1"
 	branch="$2"
-	if git_remote_branch_exists "$origin/$branch"; then
-		git_do fetch -q "$origin" "$branch" || die "Could not fetch $branch from $origin."
+	if git_remote_branch_exists "${origin}/${branch}"; then
+		git_do fetch -q "${origin}" "${branch}" || die "Could not fetch ${branch} from ${origin}."
 	else
-		warn "Trying to fetch branch '$origin/$branch' but it does not exist."
+		warn "Trying to fetch branch '${origin}/${branch}' but it does not exist."
 	fi
 }
 
@@ -280,20 +280,20 @@ gitflow_has_master_configured() {
 	local master
 
 	master=$(git config --get gitflow.branch.master)
-	[ "$master" != "" ] && git_local_branch_exists "$master"
+	[[ "${master}" != "" ]] && git_local_branch_exists "${master}"
 }
 
 gitflow_has_develop_configured() {
 	local develop
 
 	develop=$(git config --get gitflow.branch.develop)
-	[ "$develop" != "" ] && git_local_branch_exists "$develop"
+	[[ "${develop}" != "" ]] && git_local_branch_exists "${develop}"
 }
 
 gitflow_is_initialized() {
 	gitflow_has_master_configured                    && \
 	gitflow_has_develop_configured                   && \
-	[ "$(git config --get gitflow.branch.master)" != "$(git config --get gitflow.branch.develop)" ] && \
+	[[ "$(git config --get gitflow.branch.master)" != "$(git config --get gitflow.branch.develop)" ]] && \
 	git config --get-regexp gitflow.prefix >/dev/null 2>&1
 }
 
@@ -301,22 +301,22 @@ gitflow_is_initialized() {
 gitflow_load_settings() {
 	export GIT_CURRENT_REPO_DIR="$(git rev-parse --show-toplevel 2>/dev/null)"
 	DOT_GIT_DIR=$(git rev-parse --git-dir)
-	export DOT_GIT_DIR="$(cd ${DOT_GIT_DIR} >/dev/null 2>&1 && pwd)"
-	export HOOKS_DIR="$(git config --get gitflow.path.hooks || echo ${DOT_GIT_DIR}/hooks)" # the second option is used to support previous versions of git-flow
+	export DOT_GIT_DIR="$(cd "${DOT_GIT_DIR}" >/dev/null 2>&1 && pwd)"
+	export HOOKS_DIR="$(git config --get gitflow.path.hooks || echo "${DOT_GIT_DIR}"/hooks)" # the second option is used to support previous versions of git-flow
 	export MASTER_BRANCH=$(git config --get gitflow.branch.master)
 	export DEVELOP_BRANCH=$(git config --get gitflow.branch.develop)
 	export ORIGIN=$(git config --get gitflow.origin || echo origin)
 
-	GITFLOW_CONFIG="$DOT_GIT_DIR/gitflow_config"
-	if [ -f "$GITFLOW_CONFIG" ]; then # move all settings from old .git/gitflow_config to the local conf.
-		warn "Migrating old \"$GITFLOW_CONFIG\" to the \"--local\" repo config."
-		_config_lines=`git config --list --file="$GITFLOW_CONFIG"`;
+	GITFLOW_CONFIG="${DOT_GIT_DIR}/gitflow_config"
+	if [[ -f "${GITFLOW_CONFIG}" ]]; then # move all settings from old .git/gitflow_config to the local conf.
+		warn "Migrating old \"${GITFLOW_CONFIG}\" to the \"--local\" repo config."
+		_config_lines=$(git config --list --file="${GITFLOW_CONFIG}");
 		for _config_line in ${_config_lines}; do
 			_key=${_config_line%=*}
 			_value=${_config_line#=*}
-			git_do config --local gitflow.${_key} ${_value}
+			git_do config --local gitflow."${_key}" "${_value}"
 		done;
-		mv "$GITFLOW_CONFIG" "$GITFLOW_CONFIG".backup 2>/dev/null
+		mv "${GITFLOW_CONFIG}" "${GITFLOW_CONFIG}".backup 2>/dev/null
 	fi
 }
 
@@ -344,26 +344,26 @@ gitflow_resolve_nameprefix() {
 	prefix=$2
 
 	# first, check if there is a perfect match
-	if git_local_branch_exists "$prefix$name"; then
-		echo "$name"
+	if git_local_branch_exists "${prefix}${name}"; then
+		echo "${name}"
 		return 0
 	fi
 
-	matches=$(echo "$(git_local_branches)" | grep "^$(escape "$prefix$name")")
-	num_matches=$(echo "$matches" | wc -l)
-	if [ -z "$matches" ]; then
+	matches=$(echo "$(git_local_branches)" | grep "^$(escape "${prefix}${name}")")
+	num_matches=$(echo "${matches}" | wc -l)
+	if [[ -z "${matches}" ]]; then
 		# no prefix match, so take it literally
-		warn "No branches match '$prefix$name*'"
+		warn "No branches match '${prefix}${name}*'"
 		return 1
 	else
-		if [ $num_matches -eq 1 ]; then
-			echo "${matches#$prefix}"
+		if [[ "${num_matches}" -eq 1 ]]; then
+			echo "${matches#"${prefix}"}"
 			return 0
 		else
 			# multiple matches, cannot decide
-			warn "Multiple branches match prefix '$name':"
-			for match in $matches; do
-				warn "- $match"
+			warn "Multiple branches match prefix '${name}':"
+			for match in ${matches}; do
+				warn "- ${match}"
 			done
 			return 2
 		fi
@@ -377,7 +377,7 @@ gitflow_is_prefixed_branch() {
 	local branch return
 
 	branch=$1
-	case $branch in
+	case ${branch} in
 	$(git config --get gitflow.prefix.feature)* | \
 	$(git config --get gitflow.prefix.bugfix)* | \
 	$(git config --get gitflow.prefix.release)* | \
@@ -389,7 +389,7 @@ gitflow_is_prefixed_branch() {
 		return=1
 		;;
 	esac
-	return $return
+	return "${return}"
 }
 #
 # Update the config with the base of a new git-flow branch.
@@ -402,7 +402,7 @@ gitflow_config_set_base_branch() {
 
 	base=$1
 	branch=$2
-	$(git_do config --local "gitflow.branch.$branch.base" $base)
+	$(git_do config --local "gitflow.branch.${branch}.base" "${base}")
 }
 
 #
@@ -415,7 +415,7 @@ gitflow_config_get_base_branch() {
 	local branch
 
 	branch=$1
-	echo $(git config --local --get "gitflow.branch.$branch.base")
+	echo $(git config --local --get "gitflow.branch.${branch}.base")
 }
 
 #
@@ -427,7 +427,7 @@ gitflow_config_remove_base_section() {
 	local branch
 
 	branch=$1
-	$(git_do config --local --remove-section "gitflow.branch.$branch" 2>/dev/null)
+	$(git_do config --local --remove-section "gitflow.branch.${branch}" 2>/dev/null)
 }
 
 #
@@ -438,7 +438,7 @@ gitflow_config_remove_base_branch() {
 	local base
 
 	base=$1
-	$(git_do config --local --unset "gitflow.branch.$branch.base" 2>/dev/null)
+	$(git_do config --local --unset "gitflow.branch.${branch}.base" 2>/dev/null)
 }
 
 #
@@ -451,7 +451,7 @@ gitflow_config_rename_sections() {
 
 	old=$1
 	new=$2
-	$(git_do config --local --rename-section "gitflow.branch.$old" "gitflow.branch.$new" 2>/dev/null)
+	$(git_do config --local --rename-section "gitflow.branch.${old}" "gitflow.branch.${new}" 2>/dev/null)
 }
 
 # gitflow_override_flag_boolean()
@@ -464,17 +464,17 @@ gitflow_config_rename_sections() {
 gitflow_override_flag_boolean() {
 	local _variable
 
-	_variable=$(git config --bool --get gitflow.$1 2>&1)
+	_variable=$(git config --bool --get gitflow."$1" 2>&1)
 	case $? in
 	0)
-		[ "${_variable}" = "true" ] && eval "FLAGS_${2}=${FLAGS_TRUE}" || eval "FLAGS_${2}=${FLAGS_FALSE}"
+		[[ "${_variable}" = "true" ]] && eval "FLAGS_${2}=${FLAGS_TRUE}" || eval "FLAGS_${2}=${FLAGS_FALSE}"
 		;;
 	128)
 		die "${_variable}"
 		;;
 	esac
 	unset _variable
-	return ${FLAGS_TRUE}
+	return "${FLAGS_TRUE}"
 }
 
 # gitflow_override_flag_string()
@@ -487,14 +487,14 @@ gitflow_override_flag_boolean() {
 gitflow_override_flag_string() {
 	local _variable
 
-	_variable=$(git config --get gitflow.$1 2>&1)
+	_variable=$(git config --get gitflow."$1" 2>&1)
 	case $? in
 	0)
 		eval "FLAGS_${2}=\"${_variable}\""
 		;;
 	esac
 	unset _variable
-	return ${FLAGS_TRUE}
+	return "${FLAGS_TRUE}"
 }
 
 # gitflow_create_squash_message()
@@ -508,16 +508,16 @@ gitflow_override_flag_string() {
 gitflow_create_squash_message() {
 	echo Squashed commit of the following:
 	echo
-	echo $1
+	echo "$1"
 	echo
-	git log --no-merges --pretty=medium ^"$2" $3
+	git log --no-merges --pretty=medium ^"$2" "$3"
 }
 
 #
 # Parameter functions
 #
 gitflow_require_name_arg() {
-	if [ "$NAME" = "" ]; then
+	if [[ "${NAME}" = "" ]]; then
 		die_help "Missing argument <name>"
 	fi
 }
@@ -527,12 +527,12 @@ gitflow_expand_nameprefix_arg() {
 
 	gitflow_require_name_arg
 
-	expanded_name=$(gitflow_resolve_nameprefix "$NAME" "$PREFIX")
+	expanded_name=$(gitflow_resolve_nameprefix "${NAME}" "${PREFIX}")
 	exitcode=$?
-	case $exitcode in
+	case ${exitcode} in
 	0)
-		NAME=$expanded_name
-		BRANCH=$PREFIX$NAME
+		NAME=${expanded_name}
+		BRANCH=${PREFIX}${NAME}
 		;;
 	*)
 		exit 1
@@ -541,7 +541,7 @@ gitflow_expand_nameprefix_arg() {
 }
 
 gitflow_require_version_arg() {
-	if [ "$VERSION" = "" ]; then
+	if [[ "${VERSION}" = "" ]]; then
 		die_help "Missing argument <version>"
 	fi
 }
@@ -551,12 +551,12 @@ gitflow_expand_versionprefix_arg() {
 
 	gitflow_require_version_arg
 
-	version=$(gitflow_resolve_nameprefix "$VERSION" "$PREFIX")
+	version=$(gitflow_resolve_nameprefix "${VERSION}" "${PREFIX}")
 	exitcode=$?
-	case $exitcode in
+	case ${exitcode} in
 	0)
-		VERSION=$version
-		BRANCH=$PREFIX$VERSION
+		VERSION=${version}
+		BRANCH=${PREFIX}${VERSION}
 		;;
 	*)
 		exit 1
@@ -566,7 +566,7 @@ gitflow_expand_versionprefix_arg() {
 
 
 gitflow_require_base_arg() {
-	if [ "$BASE" = "" ]; then
+	if [[ "${BASE}" = "" ]]; then
 		die_help "Missing argument <base>"
 	fi
 }
@@ -576,9 +576,9 @@ gitflow_use_current_branch_name() {
 
 	current_branch=$(git_current_branch)
 
-	if startswith "$current_branch" "$PREFIX"; then
-		BRANCH=$current_branch
-		NAME=${BRANCH#$PREFIX}
+	if startswith "${current_branch}" "${PREFIX}"; then
+		BRANCH=${current_branch}
+		NAME=${BRANCH#"${PREFIX}"}
 	else
 		warn "The current HEAD is no ${SUBCOMMAND} branch."
 		warn "Please specify a <name> argument."
@@ -591,9 +591,9 @@ gitflow_use_current_branch_version() {
 
 	current_branch=$(git_current_branch)
 
-	if startswith "$current_branch" "$PREFIX"; then
-		BRANCH=$current_branch
-		VERSION=${BRANCH#$PREFIX}
+	if startswith "${current_branch}" "${PREFIX}"; then
+		BRANCH=${current_branch}
+		VERSION=${BRANCH#"${PREFIX}"}
 	else
 		warn "The current HEAD is no ${SUBCOMMAND} branch."
 		warn "Please specify a <version> argument."
@@ -607,13 +607,13 @@ gitflow_rename_branch() {
 	eval set -- "${FLAGS_ARGV}"
 
 	# read arguments into global variables
-	if [ -z $1 ]; then
+	if [[ -z "$1" ]]; then
 		NEW_NAME=''
 	else
 		NEW_NAME=$1
 	fi
 
-	if [ -z $2 ]; then
+	if [[ -z "$2" ]]; then
 		NAME=''
 	else
 		NAME=$2
@@ -621,28 +621,28 @@ gitflow_rename_branch() {
 	BRANCH=${PREFIX}${NAME}
 	NEW_BRANCH=${PREFIX}${NEW_NAME}
 
-	if [ -z "$NEW_NAME" ]; then
+	if [[ -z "${NEW_NAME}" ]]; then
 		die "No new name given."
 	fi
 
 	# Use current branch if no name is given
-	if [ "$NAME" = "" ]; then
+	if [[ "${NAME}" = "" ]]; then
 		gitflow_use_current_branch_name
 	fi
 
 
 	# Sanity checks
-	require_branch "$BRANCH"
-	require_branch_absent "$NEW_BRANCH"
+	require_branch "${BRANCH}"
+	require_branch_absent "${NEW_BRANCH}"
 
-	run_pre_hook "$NAME" "$ORIGIN" "$BRANCH"
-	git_do branch -m "$BRANCH" "$NEW_BRANCH" || die "Error renaming branch '$BRANCH' to '$NEW_BRANCH'"
-	gitflow_config_rename_sections "$BRANCH" "$NEW_BRANCH"
-	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
+	run_pre_hook "${NAME}" "${ORIGIN}" "${BRANCH}"
+	git_do branch -m "${BRANCH}" "${NEW_BRANCH}" || die "Error renaming branch '${BRANCH}' to '${NEW_BRANCH}'"
+	gitflow_config_rename_sections "${BRANCH}" "${NEW_BRANCH}"
+	run_post_hook "${NAME}" "${ORIGIN}" "${BRANCH}"
 
 	echo
 	echo "Summary of actions:"
-	echo "- Branch '$BRANCH' has been renamed to '$NEW_BRANCH'."
+	echo "- Branch '${BRANCH}' has been renamed to '${NEW_BRANCH}'."
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
 }
@@ -664,10 +664,10 @@ require_clean_working_tree() {
 
 	git_is_clean_working_tree
 	result=$?
-	if [ $result -eq 1 ]; then
+	if [[ "${result}" -eq 1 ]]; then
 		die "Working tree contains unstaged changes. Aborting."
 	fi
-	if [ $result -eq 2 ]; then
+	if [[ "${result}" -eq 2 ]]; then
 		die "Index contains uncommited changes. Aborting."
 	fi
 }
@@ -708,11 +708,11 @@ require_branches_equal() {
 	git_compare_refs "$1" "$2"
 	compare_refs_result=$?
 
-	if [ $compare_refs_result -gt 0 ]; then
+	if [[ "${compare_refs_result}" -gt 0 ]]; then
 		warn "Branches '$1' and '$2' have diverged."
-		if [ $compare_refs_result -eq 1 ]; then
+		if [[ "${compare_refs_result}" -eq 1 ]]; then
 			die "And branch '$1' may be fast-forwarded."
-		elif [ $compare_refs_result -eq 2 ]; then
+		elif [[ "${compare_refs_result}" -eq 2 ]]; then
 			# Warn here, since there is no harm in being ahead
 			warn "And local branch '$1' is ahead of '$2'."
 		else
@@ -748,13 +748,13 @@ run_filter_hook() {
 	command=$1
 	shift
 	scriptfile="${HOOKS_DIR}/filter-flow-${command}"
-	if [ -x "$scriptfile" ]; then
-		return=`$scriptfile "$@"`
-		if [ $? -eq 127 ]; then
-			echo "$return"
+	if [[ -x "${scriptfile}" ]]; then
+		return=$(${scriptfile} "$@")
+		if [[ $? -eq 127 ]]; then
+			echo "${return}"
 			exit 127
 		fi
-			echo $return
+			echo "${return}"
 	else
 		echo "$@"
 	fi
@@ -776,12 +776,12 @@ run_pre_hook() {
 
 	scriptfile="${HOOKS_DIR}/pre-flow-${SUBCOMMAND}-${SUBACTION}"
 	exitcode=0
-	if [ -x "$scriptfile" ]; then
-		"$scriptfile" "$@"
+	if [[ -x "${scriptfile}" ]]; then
+		"${scriptfile}" "$@"
 		exitcode=$?
 
-		if [ $exitcode -gt 0 ]; then
-			die "Hook command $scriptfile ended with exit code $exitcode."
+		if [[ "${exitcode}" -gt 0 ]]; then
+			die "Hook command ${scriptfile} ended with exit code ${exitcode}."
 		fi
 	fi
 }
@@ -800,11 +800,11 @@ run_post_hook() {
 	local scriptfile
 
 	scriptfile="${HOOKS_DIR}/post-flow-${SUBCOMMAND}-${SUBACTION}"
-	if [ -x "$scriptfile" ]; then
-		"$scriptfile" "$@"
+	if [[ -x "${scriptfile}" ]]; then
+		"${scriptfile}" "$@"
 	fi
 }
 
 flags_help() {
-	eval "$( echo "$OPTIONS_SPEC" | git rev-parse --parseopt -- "-h" || echo exit $? )"
+	eval "$( echo "${OPTIONS_SPEC}" | git rev-parse --parseopt -- "-h" || echo exit $? )"
 }
